from __future__ import annotations

import argparse
import pickle
import sys
from pathlib import Path
from typing import Any

from orbittrace_v6_checkpointed_fallback.common import (
    FROZEN_V6_SHA256,
    event_rows_sha256,
    load_module,
    require,
    sha256_bytes,
)

YEARS = (2022, 2023)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser()
    p.add_argument("--repaired-source", required=True, type=Path)
    p.add_argument("--checkpoint-2022", required=True, type=Path)
    p.add_argument("--checkpoint-2023", required=True, type=Path)
    p.add_argument("--base-runner", required=True, type=Path)
    p.add_argument("--support-source-parts", required=True, type=Path)
    p.add_argument("--candidate-payload", required=True, type=Path)
    p.add_argument("--baseline-payload", required=True, type=Path)
    p.add_argument("--scorer-parts", required=True, type=Path)
    p.add_argument("--fixed4-baseline-json", required=True, type=Path)
    p.add_argument("--output", required=True, type=Path)
    return p.parse_args()


def load_checkpoint(path: Path, year: int, repaired_sha: str) -> dict[str, Any]:
    raw = path.read_bytes()
    sidecar = path.with_suffix(".sha256")
    require(sidecar.exists(), f"missing checkpoint SHA sidecar {year}")
    expected = sidecar.read_text().strip().split()[0]
    require(sha256_bytes(raw) == expected, f"checkpoint SHA mismatch {year}")
    checkpoint = pickle.loads(raw)
    require(checkpoint["format"] == "orbittrace-v6-development-year-checkpoint-v1", "checkpoint format changed")
    require(int(checkpoint["year"]) == year, f"checkpoint year mismatch {year}")
    require(checkpoint["frozen_v6_sha256"] == FROZEN_V6_SHA256, "checkpoint frozen source mismatch")
    require(checkpoint["repaired_v6_sha256"] == repaired_sha, "checkpoint repaired source mismatch")
    require(checkpoint["firewall"]["target_interval_remains_excluded"] is True, "checkpoint firewall failed")
    require(checkpoint["firewall"]["hidden_labels_not_saved"] is True, "checkpoint contains hidden-label output")
    require(checkpoint["firewall"]["scientific_result_not_evaluated_in_year_job"] is True, "checkpoint stage boundary failed")
    return checkpoint


def main() -> int:
    args = parse_args()
    repaired_sha = sha256_bytes(args.repaired_source.read_bytes())
    checkpoints = {
        2022: load_checkpoint(args.checkpoint_2022, 2022, repaired_sha),
        2023: load_checkpoint(args.checkpoint_2023, 2023, repaired_sha),
    }

    v6 = load_module(args.repaired_source, "orbittrace_v6_checkpoint_replay")
    original_scan = v6.scan_year_v6

    def replay_scan(
        old: Any,
        year: int,
        events: list[dict[str, Any]],
        calibration_events: list[dict[str, Any]],
        candidate: Any,
        base: Any,
        scorer: Any,
        support: Any,
    ):
        del old, candidate, base, scorer, support
        require(year in checkpoints, f"unexpected replay year {year}")
        checkpoint = checkpoints[year]
        current_scan_sha = event_rows_sha256(events)
        current_calibration_sha = event_rows_sha256(calibration_events)
        require(current_scan_sha == checkpoint["scan_rows_sha256"], f"scan input changed before replay {year}")
        require(current_calibration_sha == checkpoint["calibration_rows_sha256"], f"calibration input changed before replay {year}")
        print(
            f"V6_CHECKPOINT_REPLAY year={year} scan_sha={current_scan_sha[:16]} "
            f"calibration_sha={current_calibration_sha[:16]}",
            flush=True,
        )
        return checkpoint["audit"], checkpoint["anchors"], checkpoint["components"]

    # The frozen repaired main() remains responsible for all catalogue parsing,
    # family construction, evaluation, preregistered gates, reporting and verdict.
    # Only its two expensive per-year scan calls are replayed from exact input-hashed
    # checkpoints generated by the same repaired scan_year_v6 implementation.
    v6.scan_year_v6 = replay_scan
    try:
        sys.argv = [
            str(args.repaired_source),
            "--base-runner", str(args.base_runner),
            "--support-source-parts", str(args.support_source_parts),
            "--candidate-payload", str(args.candidate_payload),
            "--baseline-payload", str(args.baseline_payload),
            "--scorer-parts", str(args.scorer_parts),
            "--fixed4-baseline-json", str(args.fixed4_baseline_json),
            "--output", str(args.output),
        ]
        rc = int(v6.main())
    finally:
        v6.scan_year_v6 = original_scan
    require(rc == 0, f"frozen v6 main returned {rc}")
    print("PASS_V6_CHECKPOINT_REPLAY_THROUGH_UNCHANGED_MAIN", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
