#!/usr/bin/env python3
from __future__ import annotations
import argparse,json
from pathlib import Path
import numpy as np
YEARS=(2022,2023); MONTH_KEYS=tuple(f"{y}-{m:02d}" for y in YEARS for m in range(1,13)); BLIND=(20.0,55.0); BUCKETS=(0,1,2,3)
QUALITY_SHA256="dd14e899ac08c4081cfee7d2dac2e54d2f25f78427cc4bee30f30296cd24b990"; V8_RESULT_SHA256="fa8f52cf046ced499a378cc6b7d04c52ef92bf0fa3f801049211d190f1c3919b"; STRUCTURAL_RESULT_SHA256="e8cf7d92e96db9a1c99578f6efc63baf1534b94ab975e94f789fa6bc4a718497"
def main()->int:
  ap=argparse.ArgumentParser()
  for n in ("support-cut-evaluator","prelabel","parent-runner","quality-source","support-source-parts","candidate-payload","baseline-payload","scorer-parts","v8-result-json"):ap.add_argument("--"+n,type=Path,required=True)
  ap.add_argument("--output",type=Path,required=True); a=ap.parse_args(); a.output.mkdir(parents=True,exist_ok=True)
  import importlib.util; sp=importlib.util.spec_from_file_location("levbase",a.support_cut_evaluator); base=importlib.util.module_from_spec(sp); sp.loader.exec_module(base)
  base.req(base.sha256(a.quality_source)==QUALITY_SHA256 and base.sha256(a.v8_result_json)==V8_RESULT_SHA256,"frozen input hash"); pre_sha=base.sha256(a.prelabel); pre=json.loads(a.prelabel.read_text()); base.req(pre["schema"]=="ORBITTRACE_TOPOMODAL_LINEAGE_BALANCED_V1_PRELABEL" and pre["scientific_role"]=="PRELABEL_TOPOMODAL_LINEAGE_BALANCED_V1","prelabel"); base.req(pre["structural_result_sha256"]==STRUCTURAL_RESULT_SHA256 and pre["configuration"]["ranking"]=="lineage_round_asc_then_lifetime_desc_then_family_hash","method changed"); base.req(pre["blind_exclusion"]==list(BLIND) and pre["shower_truth_used"] is False,"firewall")
  panels_map={(int(r["denominator"]),int(r["bucket"])):r for r in pre["subsets"]}; base.req(set(panels_map)=={(d,b) for d in (128,1024) for b in BUCKETS},"panel set")
  for r in pre["subsets"]:
    s=r["successor_candidates"]; p=r["recurrent_candidates"]; base.req(len(s)>=len(p) and int(r["equal_budget_k"])==len(p),"budget"); base.req([x["rank"] for x in s]==list(range(1,len(s)+1)),"rank continuity"); exp=sorted(s,key=lambda x:(int(x["lineage_round"]),-float(x["level_lifetime"]),str(x["family_hash"]))); base.req([x["family_id"] for x in s]==[x["family_id"] for x in exp],"rank order"); base.req(float(r["lineage_summary"]["diagram_reconstruction_max_abs_error"])<=1e-12,"diagram audit")
  parent=base.load_module(a.parent_runner,"lineage_eval_parent"); q=base.load_module(a.quality_source,"lineage_eval_gmn"); q.v1.mult.YEARS=YEARS; q.v1.mult.MONTH_KEYS=MONTH_KEYS; q.v1.mult.TOP_K=100; runtime=q.v1.mult.load_frozen_runtime(); support=runtime.load_support_module(a.support_source_parts); support.YEARS=YEARS; support.MONTH_KEYS=MONTH_KEYS; support.CORPUS="orbittrace-topomodal-lineage-balanced-v1-evaluator"; support.RANKING_VARIANTS=("persistence",); base.req((float(support.BLIND_LOW),float(support.BLIND_HIGH))==BLIND,"firewall changed"); setattr(a,"fixed4_baseline_json",a.v8_result_json); _c,bsrc,_s=support.load_sources(a); scan,_cal,hidden,sources=support.parse_catalogue(bsrc); base.req(isinstance(hidden,dict) and sorted(scan)==list(YEARS),"truth source")
  events=[]
  for y in YEARS:events.extend(parent.normalize_event(r,y) for r in list(scan[y]))
  base.req(len(events)==738682 and all(not(BLIND[0]<=float(e["sol"])<=BLIND[1]) for e in events),"universe/firewall"); ids=[str(e["id"]) for e in events]; yrs=np.asarray([int(e["year"]) for e in events],dtype=np.int64); hashes=np.asarray([base.hu(x) for x in ids],dtype=np.uint64); truth=[]
  for d in (128,1024):
    for b in BUCKETS:
      fr=panels_map[(d,b)]; ii=base.idx(hashes,d,b); sid=[ids[int(i)] for i in ii]; sy=np.asarray(yrs[ii]); base.req(len(sid)==int(fr["events_total"]) and base.uh(sid)==fr["event_universe_sha256"],"event universe"); K=int(fr["equal_budget_k"]); succ=fr["successor_candidates"][:K]; par=fr["recurrent_candidates"]
      for y in YEARS:
        annual={sid[int(i)] for i in np.flatnonzero(sy==y)}; pm=base.compact(parent.metrics(par,hidden,annual)); sm=base.compact(parent.metrics(succ,hidden,annual)); truth.append({"denominator":d,"bucket":b,"year":y,"equal_budget_k":K,"parent":pm,"successor":sm,"qualified_nonlower":int(sm["qualified_matches"])>=int(pm["qualified_matches"]),"qualified_strict_win":int(sm["qualified_matches"])>int(pm["qualified_matches"])})
  scales={}
  for d in (128,1024):
    ps=[p for p in truth if p["denominator"]==d]; pa=base.agg(ps,"parent"); sa=base.agg(ps,"successor"); non=sum(p["qualified_nonlower"] for p in ps); win=sum(p["qualified_strict_win"] for p in ps); scales[str(d)]={"parent":pa,"successor":sa,"qualified_nonlower_panels":non,"qualified_strict_win_panels":win,"qualified_loss_panels":8-non}
  fp,fs=scales["1024"]["parent"],scales["1024"]["successor"]; cp,cs=scales["128"]["parent"],scales["128"]["successor"]
  gates={"fine_qualified_total_strictly_greater":fs["qualified_total"]>fp["qualified_total"],"fine_qualified_nonlower_at_least_6_of_8":scales["1024"]["qualified_nonlower_panels"]>=6,"fine_mrr_mean_not_lower":fs["mrr_mean"]>=fp["mrr_mean"],"fine_precision_mean_not_lower":fs["precision_mean"]>=fp["precision_mean"],"fine_fragmentation_mean_not_higher":fs["fragmentation_mean"]<=fp["fragmentation_mean"],"coarse_qualified_total_not_lower":cs["qualified_total"]>=cp["qualified_total"],"coarse_qualified_nonlower_at_least_6_of_8":scales["128"]["qualified_nonlower_panels"]>=6,"coarse_mrr_mean_not_lower":cs["mrr_mean"]>=cp["mrr_mean"],"coarse_precision_mean_not_lower":cs["precision_mean"]>=cp["precision_mean"],"coarse_fragmentation_mean_not_higher":cs["fragmentation_mean"]<=cp["fragmentation_mean"]}
  verdict="PASS_TOPOMODAL_LINEAGE_BALANCED_V1" if all(gates.values()) else "FAIL_TOPOMODAL_LINEAGE_BALANCED_V1"; out={"schema":"ORBITTRACE_TOPOMODAL_LINEAGE_BALANCED_V1","scientific_role":"TARGET_EXCLUDED_GMN_2022_2023_SPARSE_RECOVERY_DEVELOPMENT","verdict":verdict,"prelabel_sha256":pre_sha,"structural_source_run_id":31955621864,"structural_source_artifact_id":9265889512,"structural_result_sha256":STRUCTURAL_RESULT_SHA256,"panels":truth,"scale_aggregates":scales,"gates":gates,"blind_exclusion":list(BLIND),"target_information_access":False,"target_region_events_accessed":False,"sonotaco_2013_2014_access":False,"asfn_event_level_access":False,"efn_event_level_access":False,"amos_scientific_access":False,"maarsy_scientific_access":False,"dms_scientific_access":False,"method_parameter_selection_from_result":False}; p=a.output/"TOPOMODAL_LINEAGE_BALANCED_V1.json"; p.write_text(json.dumps(out,indent=2,sort_keys=True,allow_nan=False)+"\n"); print(json.dumps({"verdict":verdict,"prelabel_sha256":pre_sha,"scales":scales,"gates":gates},indent=2,sort_keys=True),flush=True); return 0
if __name__=="__main__":raise SystemExit(main())
